export default {
    en: {
        title: 'Get in touch',
        email: 'EMAIL',
        message: 'MESSAGE',
        phone: 'PHONE NUMBER',
        string1: 'You choosed',
        name: 'NAME',
        string2: ', fill out the form & we will get in touch!',
        subtitle: 'Your package includes:',
        webPack1Feature1: 'Up to 10 views/pages',
        propousalMessage: 'COMMENTS AND INQUIRES',
        send: 'SEND',

        selectPlan: 'Select Plan',
        month: 'MONTH',

        websitesTab: 'Websites',
        webTitle: 'Web development',
        webContent: 'All our websites Plans includes: Domain Registration, Hosting Specialized Technical Support as well as the features detailed bellow. We use the latest technologies for the development and design of each web page, offering our customers functional and modern Internet pages. ',
        webPrice1: 'USD 250',
        webPrice2: 'USD 450',
        webPrice3: 'USD 625',
        webPrice4: 'USD ?',
        webPrice5: 'USD 15',
        webPrice6: 'USD 20',
        webPrice7: 'USD 20',
        webPrice8: 'USD ?',

        webPlanTitlePack1: 'Landing Page',
        webPack1Feature1: 'Up to 10 views/pages',
        webPack1Feature2: '1 custom form',
        webPack1Feature3: 'Design from templates',
        webPack1Feature4: 'Custom text/colors',

        webpack1: {
          name: 'Landing Page',
          feature1: 'Up to 10 views/pages',
          feature2: '1 custom form',
          feature3: 'Design from templates',
          feature4: 'Custom text/colors'
        },

        webPlanTitlePack2: 'Self Manageable',
        webPack2Feature1: 'Unlimited views/pages',
        webPack2Feature2: 'Self-Editable content',
        webPack2Feature3: 'Custom design',
        webPack2Feature4: 'Membership registration',
        webPack2Feature5: '2 custom form',
        webPack2Feature6: '1 month support',

        webPlanTitlePack3: 'Online Store',
        webPack3Feature1: 'Up to 100 products',
        webPack3Feature2: 'Inventory management',
        webPack3Feature3: 'Membership registration',
        webPack3Feature4: 'Custom design',
        webPack3Feature5: 'Unlimited views/pages',
        webPack3Feature6: '3 months support',

        webPlanTitlePack4: 'Custom web',
        webPack4Feature1: 'Tell us your idea of a kickass website and what would you like to have in it',

        socialTab: 'Social Marketing',
        socialTitle: 'Social Media',
        socialContent: 'Manage your entire social lifecycle. From one dashboard you’ll schedule Tweets and Facebook posts, monitor conversations, and more. When you need to prove your social ROI, quickly create and customize ready-to-present analytics reports.',
        socialPrice1: 'USD 250',
        socialPrice2: 'USD 450',
        socialPrice3: 'USD 625',
        socialPrice4: 'USD ?',

        socialPack1Feature1: '5 tabs or views',
        socialPack1Feature2: '1 custom form',
        socialPack1Feature3: 'Design from templates',
        socialPack1Feature4: 'Custom text/colors',

        socialPack2Feature1: '5 tabs or views',
        socialPack2Feature2: '1 custom form',
        socialPack2Feature3: 'Design from templates',
        socialPack2Feature4: 'Custom text/colors',

        socialPack3Feature1: '5 tabs or views',
        socialPack3Feature2: '1 custom form',
        socialPack3Feature3: 'Design from templates',
        socialPack3Feature4: 'Custom text/colors',

        socialPack4Feature1: 'Tell us your idea of a kickass social plan and what would you like to have in it',

        mobileTab: 'Apps móbiles',
        mobileTitle: 'Mobile/Tablet application development',
        mobileContent: 'All the aplications are developed for the following platforms: IOS (Iphone and Ipad) as well as ANDROID in their most known versions. It also includes one Splash Screen and a website platform for the management of the Online Store App and the Reservations App. Delivery: 20 days (after the client provides the content and images for development)',
        mobilePrice1: 'USD 900',
        mobilePrice2: 'USD 1100',
        mobilePrice3: 'USD 1000',
        mobilePrice4: 'USD ?',

        mobilePlanTitlePack1: 'Landing Page',
        mobilePack1Feature1: 'Up to 10 views',
        mobilePack1Feature2: '1 custom form',
        mobilePack1Feature3: 'Design from templates',
        mobilePack1Feature4: 'Custom text/colors',

        mobilePlanTitlePack2: 'Self Manageable',
        mobilePack2Feature1: 'Custom design',
        mobilePack2Feature2: 'Inventory management',
        mobilePack2Feature3: 'Up to 100 productos',
        mobilePack2Feature4: '1 months support',
        mobilePack2Feature5: 'Membership registration',
        mobilePack2Feature6: 'Unlimited views/pages',

        mobilePlanTitlePack3: 'Online Store',
        mobilePack3Feature1: 'Custom design',
        mobilePack3Feature2: 'Reservation management',
        mobilePack3Feature3: 'Membership registration',
        mobilePack3Feature4: '1 months support',
        mobilePack3Feature5: 'Membership registration',
        mobilePack3Feature6: 'Unlimited views/pages',

        mobilePlanTitlePack4: 'Custom App',
        mobilePack4Feature1: 'Tell us your idea of a kickass app and what would you like to have in it',

    },
    es: {
      title: 'Contactanos',
      email: 'CORREO',
      message: 'MENSAJE',
      phone: 'NUMERO DE TELEFONO',
      string1: 'Elegiste',
      name: 'NOMBRE',
      string2: ', rellena tus datos y te contactaremos!',
      webPack1Feature1: 'Up to 10 views/pages',
      subtitle: 'Tu paquete incluye:',
      propousalMessage: 'COMENTARIOS Y PREGUNTAS',
      send: 'ENVIAR',
      
      selectPlan: 'Elegir Plan',
      month: 'MES',

      websitesTab: 'Paginas web',
      webTitle: 'Desarrollo Web',
      webContent: 'Todos los Planes de websites incluyen: Registro de Dominio, Hosting, Soporte Técnico Especializado y las caracteristicas detalladas en cada paquete. Utilizamos las ultimas tecnologías para el desarrollo y diseño de cada página web, ofreciendo a nuestros clientes páginas de Internet funcionales y modernas.',
      webPrice1: '$ 4000',
      webPrice2: '$ 7000',
      webPrice3: '$ 10000',
      webPrice4: '$ ?',
      webPrice5: '$ 200',
      webPrice6: '$ 300',
      webPrice7: '$ 300',
      webPrice8: '$ ?',

      webPlanTitlePack1: 'Web Simple',
      webPack1Feature1: 'Hasta 10 vistas/paginas',
      webPack1Feature2: '1 formulario personalizados',
      webPack1Feature3: 'Diseño de plantilla',
      webPack1Feature4: 'Textos/colores personalizados',

      webPlanTitlePack2: 'Web Auto-administrable',
      webPack2Feature1: 'Vistas/paginas ilimitadas',
      webPack2Feature2: 'Auto-administrable',
      webPack2Feature3: 'Diseño personalizado',
      webPack2Feature4: 'Registro de usuarios',
      webPack2Feature5: '2 formularios',
      webPack2Feature6: '1 mes de soporte',

      webPlanTitlePack3: 'Tienda Online',
      webPack3Feature1: 'Hasta 100 productos',
      webPack3Feature2: 'Manejo de inventario',
      webPack3Feature3: 'Registro de usuarios',
      webPack3Feature4: 'Diseño personalizado',
      webPack3Feature5: 'Vistas/paginas ilimitadas',
      webPack3Feature6: '3 meses de soporte',

      webPlanTitlePack4: 'Web personalizada',
      webPack4Feature1: 'Contanos tu idea de website y que deberia tener/hacer!',

      socialTab: 'Marketing Social',
      socialTitle: 'Redes sociales',
      socialContent: 'Manejamos tu cartera de redes sociales. From one dashboard you’ll schedule Tweets and Facebook posts, monitor conversations, and more. When you need to prove your social ROI, quickly create and customize ready-to-present analytics reports.',
      socialPrice1: '$ 4000',
      socialPrice2: '$ 7000',
      socialPrice3: '$ 1000',
      socialPrice4: '$ ?',
      socialPack1Feature1: '5 tabs or views',
      socialPack1Feature2: '1 custom form',
      socialPack1Feature3: 'Design from templates',
      socialPack1Feature4: 'Custom text/colors',

      socialPack2Feature1: '15 tabs or views',
      socialPack2Feature2: '2 custom form',
      socialPack2Feature3: 'Custom design',
      socialPack2Feature4: 'Users management',
      socialPack2Feature5: 'Google AdWords',
      socialPack2Feature6: '1 month support',

      socialPack3Feature1: '30 tabs or views',
      socialPack3Feature2: '3 custom forms',
      socialPack3Feature3: 'Users management',
      socialPack3Feature4: 'Custom design',
      socialPack3Feature5: 'Google AdWords',
      socialPack3Feature6: '3 months support',

      socialPack4Feature1: 'Contanos tu idea de plan social y que deberia tener/hacer!',

      mobileTab: 'Mobile Apps',
      mobileTitle: 'Desarrollo de aplicaciones para Celulares/Tablets',
      mobileContent: 'Todas las aplicaciones estan desarrolladas para dispositivos con plataformas IOS (Iphone y Ipad) como tambien ANDROID en sus formatos mas comunes. Tambien incluyen la edicion de la Splash Screen y una plataforma web para la administration de la Tienda online App y la Reservas online App. Plazo de entrega: 20 dias (despues de entregado los contenidos e imagenes por el cliente)',
      mobilePrice1: '$ 12000',
      mobilePrice2: '$ 18000',
      mobilePrice3: '$ 17000',
      mobilePrice4: '$ ?',

      mobilePlanTitlePack1: 'Simple App',
      mobilePack1Feature1: 'Hasta 10 vistas',
      mobilePack1Feature2: '1 formulario personalizado',
      mobilePack1Feature3: 'Diseño de plantilla',
      mobilePack1Feature4: 'Textos/colores personalizados',

      mobilePlanTitlePack2: 'Tienda Online',
      mobilePack2Feature1: 'Páginas ilimitadas',
      mobilePack2Feature2: 'Manejo de inventario',
      mobilePack2Feature3: 'Diseño personalizado',
      mobilePack2Feature4: 'Hasta 100 productos',
      mobilePack2Feature5: '1 mes de soporte',
      mobilePack2Feature6: 'Registro de usuarios',

      mobilePlanTitlePack3: 'App Auto-administrable',
      mobilePack3Feature1: 'Vistas/paginas ilimitadas',
      mobilePack3Feature2: 'Manejo de reservas',
      mobilePack3Feature3: 'Diseño personalizado',
      mobilePack3Feature4: 'Registro de usuarios',
      mobilePack3Feature5: '1 mes de soporte',
      mobilePack3Feature6: 'Registro de usuarios',

      mobilePlanTitlePack4: 'App customizable',
      mobilePack4Feature1: 'Contanos tu idea de aplicacion y que deberia tener/hacer!',
   }
}
