export default {
    en: {
      title: 'Get in touch',
      email: 'EMAIL',
      message: 'MESSAGE',
      phone: 'PHONE NUMBER',
      string1: 'You choosed',
      name: 'NAME',
      string2: ', fill out the form & we will get in touch!',
      subtitle: 'Your package includes:',
      propousalMessage: 'COMMENTS AND INQUIRES',
      send: 'SEND',

      webPack1Name: 'Landing Page',
      webPack1subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      webPack1Feature1: 'Up to 10 views/pages',
      webPack1Feature2: '1 custom form',
      webPack1Feature3: 'Design from templates',
      webPack1Feature4: 'Custom text/colors',

      webPack2Name: 'Auto-administrable page',
      webPack2subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      webPack2Feature1: 'Unlimited views/pages',
      webPack2Feature2: 'Self-Editable content',
      webPack2Feature3: 'Custom design',
      webPack2Feature4: 'Membership registration',
      webPack2Feature5: '2 custom form',
      webPack2Feature6: '1 month support',

      webPack3Name: 'Online Store',
      webPack3subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      webPack3Feature1: 'Up to 100 products',
      webPack3Feature2: 'Inventory management',
      webPack3Feature3: 'Membership registration',
      webPack3Feature4: 'Custom design',
      webPack3Feature5: 'Unlimited views/pages',
      webPack3Feature6: '3 months support',

      webPack4Name: 'Custom Page',
      webPack3subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      webPack4Feature1: 'Tell us your idea of a kickass website and what would you like to have in it. If possible add websites links that you have on mind to take some ideas of.. :)',

      socialTab: 'Social Media Management',
      socialTitle: 'Social Media',
      socialContent: 'Manage your entire social lifecycle. From one dashboard you’ll schedule Tweets and Facebook posts, monitor conversations, and more. When you need to prove your social ROI, quickly create and customize ready-to-present analytics reports.',
      socialPrice1: 'USD 250',
      socialPrice2: 'USD 450',
      socialPrice3: 'USD 625',
      socialPrice4: 'USD ?',

      socialPack1Name: 'Landing Page',
      socialPack1Feature1: '5 tabs or views',
      socialPack1Feature2: '1 custom form',
      socialPack1Feature3: 'Design from templates',
      socialPack1Feature4: 'Custom text/colors',

      socialPack2Name: 'Landing Page',
      socialPack2Feature1: '5 tabs or views',
      socialPack2Feature2: '1 custom form',
      socialPack2Feature3: 'Design from templates',
      socialPack2Feature4: 'Custom text/colors',

      socialPack3Name: 'Landing Page',
      socialPack3Feature1: '5 tabs or views',
      socialPack3Feature2: '1 custom form',
      socialPack3Feature3: 'Design from templates',
      socialPack3Feature4: 'Custom text/colors',

      socialPack4Name: 'Landing Page',
      socialPack4Feature1: 'Tell us your idea of a kickass social plan and what would you like to have in it. If possible add websites links that you have on mind to take some ideas of.. :)',

      mobileTab: 'Applications for phones/tablets',
      mobileTitle: 'Mobile/Tablet application development',
      mobileContent: 'All the aplications are developed for the following platforms: IOS (Iphone and Ipad) as well as ANDROID in their most known versions. It also includes one Splash Screen and a website platform for the management of the Online Store App and the Reservations App. Delivery: 20 days (after the client provides the content and images for development)',
      mobilePrice1: 'USD 900',
      mobilePrice2: 'USD 1100',
      mobilePrice3: 'USD 1000',
      mobilePrice4: 'USD ?',

      mobilePack1Name: 'Landing Page App',
      mobilePack1subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack1Feature1: 'Up to 10 views',
      mobilePack1Feature2: '1 custom form',
      mobilePack1Feature3: 'Design from templates',
      mobilePack1Feature4: 'Custom text/colors',

      mobilePack2Name: 'Auto-administrable App',
      mobilePack2subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack2Feature1: 'Custom design',
      mobilePack2Feature2: 'Inventory management',
      mobilePack2Feature3: 'Up to 100 productos',
      mobilePack2Feature4: '1 months support',
      mobilePack2Feature5: 'Membership registration',
      mobilePack2Feature6: 'Unlimited views/pages',

      mobilePack3Name: 'Online Store',
      mobilePack3subheading: 'We have more than features fifty completely different templates, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack3Feature1: 'Custom design',
      mobilePack3Feature2: 'Reservation management',
      mobilePack3Feature3: 'Membership registration',
      mobilePack3Feature4: '1 months support',
      mobilePack3Feature5: 'Membership registration',
      mobilePack3Feature6: 'Unlimited views/pages',

      mobilePack4Name: 'Custom App',
      mobilePack4subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack4Feature1: 'Tell us your idea of a kickass app and what would you like to have in it. If possible add websites links that you have on mind to take some ideas of.. :)',
    },
    es: {
      title: 'Contactanos',
      email: 'CORREO',
      message: 'MENSAJE',
      phone: 'NUMERO DE TELEFONO',
      string1: 'Elegiste',
      name: 'NOMBRE',
      string2: ', rellena tus datos y te contactaremos!',
      subtitle: 'Tu paquete incluye:',
      propousalMessage: 'COMENTARIOS Y PREGUNTAS',
      send: 'ENVIAR',

      webPack1Name: 'Página Simple',
      webPack1subheading: 'Tenemos más de cincuenta plantillas completamente diferentes, con diseños simples y limplios. Esto es sólo un vistazo de lo que usted puede lograr mediante el uso de cada demo. Compruebe y elija el que se ajuste a sus necesidades',
      webPack1Feature1: 'Hasta 10 vistas/paginas',
      webPack1Feature2: '1 formulario personalizados',
      webPack1Feature3: 'Diseño de plantilla',
      webPack1Feature4: 'Textos/colores personalizados',

      webPack2Name: 'Web Auto-administrable',
      webPack2subheading: 'Tenemos más de cincuenta plantillas completamente diferentes, con diseños simples y limplios. Esto es sólo un vistazo de lo que usted puede lograr mediante el uso de cada demo. Compruebe y elija el que se ajuste a sus necesidades',
      webPack2Feature1: 'Vistas/paginas ilimitadas',
      webPack2Feature2: 'Auto-administrable',
      webPack2Feature3: 'Diseño personalizado',
      webPack2Feature4: 'Registro de usuarios',
      webPack2Feature5: '2 formularios',
      webPack2Feature6: '1 mes de soporte',

      webPack3Name: 'Tienda online',
      webPack3subheading: 'Tenemos más de cincuenta plantillas completamente diferentes, con diseños simples y limplios. Esto es sólo un vistazo de lo que usted puede lograr mediante el uso de cada demo. Compruebe y elija el que se ajuste a sus necesidades',
      webPack3Feature1: 'Hasta 100 productos',
      webPack3Feature2: 'Manejo de inventario',
      webPack3Feature3: 'Registro de usuarios',
      webPack3Feature4: 'Diseño personalizado',
      webPack3Feature5: 'Vistas/paginas ilimitadas',
      webPack3Feature6: '3 meses de soporte',

      webPack4Name: 'Página a medida',
      webPack4subheading: 'Tenemos más de cincuenta plantillas completamente diferentes, con diseños simples y limplios. Esto es sólo un vistazo de lo que usted puede lograr mediante el uso de cada demo. Compruebe y elija el que se ajuste a sus necesidades',
      webPack4Feature1: 'Contanos tu idea de website y que deberia tener/hacer!. Si es posible agregá tambien links de páginas web que tengas en mente para sacar ideas :)',

      socialTab: 'Manejo de redes sociales',
      socialTitle: 'Redes sociales',
      socialContent: 'Manejamos tu cartera de redes sociales. From one dashboard you’ll schedule Tweets and Facebook posts, monitor conversations, and more. When you need to prove your social ROI, quickly create and customize ready-to-present analytics reports.',
      socialPrice1: '$ 4000',
      socialPrice2: '$ 7000',
      socialPrice3: '$ 1000',
      socialPrice4: '$ ?',

      socialPack1Name: 'Landing Page',
      socialPack1Feature1: '5 tabs or views',
      socialPack1Feature2: '1 custom form',
      socialPack1Feature3: 'Design from templates',
      socialPack1Feature4: 'Custom text/colors',

      socialPack2Name: 'Landing Page',
      socialPack2Feature1: '15 tabs or views',
      socialPack2Feature2: '2 custom form',
      socialPack2Feature3: 'Custom design',
      socialPack2Feature4: 'Users management',
      socialPack2Feature5: 'Google AdWords',
      socialPack2Feature6: '1 month support',

      socialPack3Name: 'Landing Page',
      socialPack3Feature1: '30 tabs or views',
      socialPack3Feature2: '3 custom forms',
      socialPack3Feature3: 'Users management',
      socialPack3Feature4: 'Custom design',
      socialPack3Feature5: 'Google AdWords',
      socialPack3Feature6: '3 months support',

      socialPack4Name: 'Landing Page',
      socialPack4Feature1: 'Contanos tu idea de plan social y que deberia tener/hacer!. Si es posible agregá tambien links de páginas web que tengas en mente para sacar ideas :)',

      mobileTab: 'Aplicaciones para Celulares/Tablets',
      mobileTitle: 'Desarrollo de aplicaciones para Celulares/Tablets',
      mobileContent: 'Todas las aplicaciones estan desarrolladas para dispositivos con plataformas IOS (Iphone y Ipad) como tambien ANDROID en sus formatos mas comunes. Tambien incluyen la edicion de la Splash Screen y una plataforma web para la administration de la Tienda online App y la Reservas online App. Plazo de entrega: 20 dias (despues de entregado los contenidos e imagenes por el cliente)',
      mobilePrice1: '$ 12000',
      mobilePrice2: '$ 18000',
      mobilePrice3: '$ 17000',
      mobilePrice4: '$ ?',

      mobilePack1Name: 'Simple App',
      mobilePack1subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack1Feature1: 'Hasta 10 vistas',
      mobilePack1Feature2: '1 formulario personalizado',
      mobilePack1Feature3: 'Diseño de plantilla',
      mobilePack1Feature4: 'Textos/colores personalizados',

      mobilePack2Name: 'Web Auto-administrable',
      mobilePack2subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack2Feature1: 'Vistas/paginas ilimitadas',
      mobilePack2Feature2: 'Manejo de inventario',
      mobilePack2Feature3: 'Diseño personalizado',
      mobilePack2Feature4: 'Hasta 100 productos',
      mobilePack2Feature5: '1 mes de soporte',
      mobilePack2Feature6: 'Registro de usuarios',

      mobilePack3Name: 'Tienda online App',
      mobilePack3subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack3Feature1: 'Vistas/paginas ilimitadas',
      mobilePack3Feature2: 'Manejo de reservas',
      mobilePack3Feature3: 'Diseño personalizado',
      mobilePack3Feature4: 'Registro de usuarios',
      mobilePack3Feature5: '1 mes de soporte',
      mobilePack3Feature6: 'Registro de usuarios',

      mobilePack4Name: 'Custom App',
      mobilePack4subheading: 'Intact features eight completely different, clean designed demo websites. This is just a glimpse of what you can achive by using the theme. Check and choose the one that suites your needs',
      mobilePack4Feature1: 'Contanos tu idea de aplicacion y que deberia tener/hacer!',

    }
}
