export default {
    en: {
        back: 'Back',
        category: 'Category',
        service: 'Service',
        delete: 'Delete',
        description: 'Description',
        enabled: 'Enabled',
        fieldRequired: 'This field is required',
        homepage: 'Homepage',
        homepageFeatured: 'Homepage Featured',
        mainNavigation: 'Main Navigation',
        name: 'Name',
        parent: 'Parent Service',
        save: 'Save',
        sections: 'Featured in Sections',
        pricing: 'Pricing',
        currency: 'Currency',
        arsprice: 'Precio en ARS',
        USDprice: 'Precio en USD',
        title: 'Edit Service',
        type: 'Type',
        deleteServiceModalTitle: 'You confirme the deletion?',
    },
    es: {
        back: 'Volver',
        category: 'Categoría',
        service: 'Servicio',
        delete: 'Remover',
        description: 'Descripción',
        enabled: 'Activada',
        fieldRequired: 'Este campo es obligatorio',
        homepage: 'Página Principal',
        homepageFeatured: 'Destacados de Página Principal',
        mainNavigation: 'Menu Principal',
        name: 'Nombre',
        parent: 'Servicio Base',
        save: 'Guardar',
        sections: 'Destacados en Secciones',
        pricing: 'Precio',
        currency: 'Currency',
        usdprice: 'Precio en USD',
        arsprice: 'Precio en ARS',
        title: 'Editar Servicio',
        type: 'Tipo',
        deleteServiceModalTitle: 'Desea confirmar la eliminacion?',
    }
};
